// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const cloneElement: typeof import('react')['cloneElement']
  const createContext: typeof import('react')['createContext']
  const createElement: typeof import('react')['createElement']
  const forwardRef: typeof import('react')['forwardRef']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
}
export {}
